### ISSUE TITLE
Doesn't handle nested resources

### ISSUE THREAD

**Issue by bibliotechy** [upenn-libraries/ezwadl#1]
WADL's can have nested resources, for example this [Alma Users WADL](https://developers.exlibrisgroup.com/resources/wadl/0aa8d36f-53d6-48ff-8996-485b90b103e4.wadl), but EzWadl only creates a resource entry at the top level.

**Comment by bibliotechy** [comment]
Never mind, it appears I just didn't understand how to access those sub-resources.

**Comment by Null-Is-Null** [comment]
I think the documentation is a bit unclear with respect to this bit of functionality. I'll update the README accordingly.
